#!/bin/csh

set DEBUG = 0


#
# Script to generate ops summary
#


set TEL_HOME=/usr/local/livedata
set JAR_HOME=/usr/local/livedata/common


if ($DEBUG) echo "Setting environments"


# get class files.
#setenv CLASSPATH /usr/local/livedata/class
setenv CLASSPATH

foreach file (${JAR_HOME}/ngat/*.jar)
    setenv CLASSPATH ${CLASSPATH}:$file
    if ($DEBUG) echo "Add $file"
end

setenv CLASSPATH /usr/local/livedata/newclass/new.jar:$CLASSPATH


if ( ! ${?LD_LIBRARY_PATH} ) then
   setenv LD_LIBRARY_PATH /lib:/usr/lib:/usr/X11R6/lib:/usr/local/lib/:.
endif

setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${JAR_HOME}/lib

# set JAVA=/usr/java/jdk1.6.0_16/bin/java
set JAVA=/usr/bin/java


cd $TEL_HOME

set EGD = "-Djava.security.egd=file:/dev/urandom"
 
set HH = `date -u "+%H"` 
if ($DEBUG) echo "The hour is $HH "

if ($HH >= 12) then
    if ($DEBUG) echo "Evening going for lunchtime today..."
    set DAT = `date -u "+%Y-%m-%dT%H:%M:%S" -d "1200"`
    if ($DEBUG) echo "Set date to $DAT "
else
    if ($DEBUG) echo "Morning so use yesterday lunchtime..."
    set DAT = `date -u "+%Y-%m-%dT%H:%M:%S" -d "yesterday 1200"`     
    if ($DEBUG) echo "Set date to $DAT "        
endif



if ($DEBUG) echo "Generate  /var/www/html/Ops/current_ops.png"
if ($DEBUG) then
  $JAVA ngat.rcsgui.test.OperationsTimeSlicer --start $DAT --nd 1 --file /home/eng/public_html/oas_lt.dat --write --output /var/www/html/Ops/current_ops.png 
else
  $JAVA ngat.rcsgui.test.OperationsTimeSlicer --start $DAT --nd 1 --file /home/eng/public_html/oas_lt.dat --write --output /var/www/html/Ops/current_ops.png >& /dev/null
endif

if ($DEBUG) echo "Generate  /var/www/html/Ops/current_ops2.png"
if ($DEBUG) then
  $JAVA ngat.rcsgui.test.OperationsTimeSlicer --start $DAT --nd 1 --file /home/eng/public_html/oas_lt.dat --colors /home/eng/tmp/alt.properties --write --output /var/www/html/Ops/current_ops2.png 
else
  $JAVA ngat.rcsgui.test.OperationsTimeSlicer --start $DAT --nd 1 --file /home/eng/public_html/oas_lt.dat --colors /home/eng/tmp/alt.properties --write --output /var/www/html/Ops/current_ops2.png >& /dev/null  
endif


