#!/bin/sh

# ---------------------------------------------------
# Init Launcher for: Telem
# ---------------------------------------------------

/etc/rc.d/init.d/functions

TELEM_LOG=/usr/local/livedata/live.log

case "$1" in
  start)
	echo "Starting Telem Receiver. "
	/usr/local/livedata/bin/telem start 1>> ${TELEM_LOG} 2>&1 & 
	;;
  stop)
	echo "Shutting down Telem Receiver."
	/usr/local/livedata/bin/telem stop 1>> ${TELEM_LOG} 2>&1 &     
	;;
  restart)
	$0 stop
	echo "Restarting in 10 secs" 
	sleep 10
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
